### ISSUE TITLE
MT9v034 Camera

### ISSUE THREAD

**Issue by doctorluhang** [PX4/Flow#79]
Dear all,
I have a simple question. Can I change the camera sensor to another one? Since this sensor mt9v034 requires a lens that is pretty large, I want to change it into another smaller camera such as OVA7670, etc. Can I do that?

**Comment by LorenzMeier** [comment]
As long as its global shutter yes.

**Comment by doctorluhang** [comment]
@LorenzMeier Thanks for your quick reply. Could you please tell me why it requires global shutter? IMHO, it only captures the video frames that seemingly does not need to shutter. Besides, MT9v034 has pins of exposure and standby. Are these functions used in calculating in optical flow?

**Comment by tpetri** [comment]
He was talking about the electrical shutter of the image sensor. If you don't want to have a global shutter, you most likely mean a rolling shutter sensor, then I would suggest to take the [rolling shutter effect](https://en.wikipedia.org/wiki/Rolling_shutter) into consideration. This is something that you don't want to have because the existing code assumes that there are no rolling shutter effects in the images and it would lead to potentially very distorted estimations.
